---
meta:
  name:    quick-uaa-deployment-cf
  target:  ohio-cf
  url:     https://ci2.starkandwayne.com

  initial_version: 1.4.0

  aws:
    region_name: us-east-2
    access_key: ((aws-cfcommunity-access))
    secret_key: ((aws-cfcommunity-secret))

  git:
    email:  ((git-commit-email))
    name:   ((git-commit-name))

  github:
    owner:  starkandwayne
    repo:   quick-uaa-deployment-cf
    branch: develop
    private_key:  ((github-private-key))
    access_token: ((github-access-token))

  cf:
    url:      https://api.run.pivotal.io
    username: ((cf-pws-username))
    password: ((cf-pws-password))
    organization: starkandwayne
    space:        uaa-deployment-cf-test
    test_route:   uaa-deployment-cf-test.cfapps.io

  slack:
    webhook:  ((slack-webhook))
    icon:     ((slack-logo))
    username: ((slack-username))